### ISSUE TITLE
change city boundary Rome

### ISSUE THREAD

**Issue by nataliemueller** [masalmon/fietsen#4]
all data for Rome will change with the new city boundary.

**Comment by maelle** [comment]
Now I use GADM for Roma too.

**Comment by nataliemueller** [comment]
Is all the data updated already for the new boundaries?

**Comment by maelle** [comment]
No, the queries are being made now :smiley_cat:

**Comment by nataliemueller** [comment]
how do I know when its done and updated?

**Comment by nataliemueller** [comment]
ha I guess by the indicated time
