### ISSUE TITLE
updates data with new boundaries

### ISSUE THREAD

**Issue by maelle** [masalmon/fietsen#5]
underway on my PC, I'll upload the data on Wednesday @nataliemueller

**Comment by nataliemueller** [comment]
for Örebro and Rome, right? The rest stays the same?

**Comment by maelle** [comment]
The query will update everything, so if more geocoding has taken place, the other numbers can change  (but probably only a little)

**Comment by maelle** [comment]
Mmh something went wrong I'll correct that soon.
